export default [
  {
    id:1,
    title:"StarBucks 클론코딩",
    date:"제작기간 : 2021.08월",
    content:"첫 프론트엔드 개발을 시작하면서 만들어본 StarBucks 사이트입니다.",
    content2:"Html,css,JavaScript 를 사용하여 제작하였습니다. Html을 처음 접해보면서 block 요소와 inline 요소를 공부하여 적용해보았고,다양한 태그들의 의미를생각하면서 사용했습니다. css는 가상요소들과 hover,다양한 애니메이션 효과 를 공부하여 적용하였습니다.JavaScript 에서는 슬라이더 효과는swiper.js, scroll.js 를 사용하여 제작했습니다.",
    function:"슬라이더, Top 버튼, 애니메이션효과",
    githubad:"https://github.com/sangboking/starbucks",
    github:"github.com/sangboking/starbucks",
    pagead:"https://frosty-goldwasser-d09f3d.netlify.app/",
    page:"frosty-goldwasser-d09f3d.netlify.app/",
    skill:"Html, css, JavaScript"
  },
  {
    id:2,
    title:"Food Page",
    date:" 2021.10월",
    content:"css 반응형을 중점적으로 두고 제작하였습니다.",
    content2:"미디어 쿼리를 처음 사용해보면서 반응형 웹페이지를 중점적으로제작하였습니다. Grid 형태의 레이아웃을 통해 제작하였고 애니메이션효과를 적용하였습니다. JavaScript 에서는 swiper.js를 사용하였습니다.",
    function:"슬라이더, 반응형웹",
    githubad:"https://github.com/sangboking/Food-page",
    github:"github.com/sangboking/Food-page",
    pagead:"https://focused-swanson-205029.netlify.app",
    page:"focused-swanson-205029.netlify.app",
    skill:"Html, css, JavaScript"
  },
  {
    id:3,
    title:"React 쇼핑몰",
    date:"제작기간 : 2021.11월",
    content:"React를 사용하여 제작한 간단한 기능의 쇼핑몰입니다.",
    content2:"React를 처음 사용하면서 제작한 React.js 기반의 웹사이트입니다.React의 기본적인 기능을 사용하여 구현하였습니다. props의 불편한점을 해소하기 위하여 Redux를 공부하여 적용해 보았습니다.",
    function:"주문기능, 수량증감, 모달창",
    githubad:"https://github.com/sangboking/reactshop",
    github:"github.com/sangboking/reactshop",
    pagead:"https://sangboking.github.io/reactshop/#/",
    page:"sangboking.github.io/#/",
    skill:"React, Redux, Scss"
  },
  {
    id:4,
    title:"포트폴리오 웹사이트",
    date:"제작기간 : 2021.11월",
    content:"React를 사용하여 제작한 포트폴로 입니다.",
    content2:"React 를 사용하여 section 을 components로 나누어 제작하였습니다.",
    function:"스크롤다운시 헤더변경, Totop버튼, Intro타이핑 효과",
    githubad:"https://github.com/sangboking/reactshop",
    github:"github.com/sangboking/portfolio",
    pagead:"https://sangboking.github.io/portfolio/",
    page:"sangboking.github.io/portfolio/",
    skill:"React, Scss"
  },
  {
    id:5,
    title:"Todo List",
    date:"제작기간 : 2021.12월",
    content:"React를 사용한 Todo List 입니다.",
    content2:"React의 훅들을 이용하여 내가할일 추가,토글,삭제 기능을 구현하였습니다.",
    function:"List 추가,삭제,토글",
    githubad:"https://github.com/sangboking/todolist",
    github:"github.com/sangboking/todolist",
    pagead:"https://sangboking.github.io/todolist/",
    page:"sangboking.github.io/todolist/",
    skill:"React, Scss"
  },
  {
    id:6,
    title:"Movie App",
    date:"제작기간 : 2021.1월",
    content:"React를 사용한 Movie App 입니다.",
    content2:"Movie API를 받아 화면에 간단하게 구현한 사이트입니다.비동기 처리인 async await에 대해 깊게학습할수 있었고, react-router-dom의 6버전이 나오면서 바뀐 내용을 적용하여 사용하였습니다.",
    function:"API처리, Router처리",
    githubad:"https://github.com/sangboking/todolist",
    github:"github.com/sangboking/react-movieapp",
    pagead:"https://sangboking.github.io/react-movieapp/",
    page:"sangboking.github.io/react-movieapp/",
    skill:"React, Scss"
  }
]